#os: linux
#language: android
#jdk: openjdk11
#sudo: required
#
#android:
#  components:
#    - tools
#    - tools
#    - platform-tools
#    - build-tools-30.0.2
#    #- android-30
#    #- android-31
#    - android-29
#    - android-29
#    #- android-24
#    #- sys-img-armeabi-v7a-android-24
#    #- sys-img-
#    - sys-img-x86-android-29
#    - extra-android-m2repository
#    - extra-google-m2repository
#    - extra-android-support
#    - extra-google-google_play_services
##env:
##  global:
##    - TARGET_VERSION=29
##    - ANDROID_API_LEVEL=29
##    #- ANDROID_ABI=armeabi-v7a
##    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
##    - ANDROID_HOME=~/android-sdk
##    - QEMU_AUDIO_DRV=none
##    - ANDROID_SDK_ROOT=$ANDROID_HOME
#
##before_install:
##  - touch $HOME/.android/repositories.cfg
##  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip" -O commandlinetools.zip
##  - unzip commandlinetools.zip -d $ANDROID_HOME/
##  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
##  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME
#
#before_script:
#  # Create and start emulator
#  - android list targets
#  #- chmod +x gradlew
#  - echo no | android create avd --force -n test -t android-29 --abi x86
#  - emulator -avd test -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
#
#script: ./gradlew connectedAndroidTest

sudo: required
language: android
jdk: oraclejdk11
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra
before_install:
  - echo yes | sdkmanager "build-tools;29.0.3"
  - echo yes | sdkmanager "platforms;android-29"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - sdkmanager "system-images;android-29;google_apis;x86"
  - echo no | avdmanager create avd --force -n emulatorApi29 -k "system-images;android-29;google_apis;x86"
  - emulator -avd test -no-audio -no-window &
  - ./gradlew dependencies || true
before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build connectedCheck
  - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
before_cache:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
#cache:
#  directories:
#    -$HOME/.gradle/caches/
#    -$HOME/.gradle/wrapper/s
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'