#os: linux
#language: android
#jdk: openjdk11
#
#android:
#  components:
#    - tools
#    - tools
#    - platform-tools
#    - build-tools-30.0.2
#    #- android-30
#    #- android-31
#    - android-29
#    - android-29
#    #- android-24
#    #- sys-img-armeabi-v7a-android-24
#    #- sys-img-
#    - sys-img-x86-android-29
#    - extra-android-m2repository
#    - extra-google-m2repository
#    - extra-android-support
#    - extra-google-google_play_services
##env:
##  global:
##    - TARGET_VERSION=29
##    - ANDROID_API_LEVEL=29
##    #- ANDROID_ABI=armeabi-v7a
##    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
##    - ANDROID_HOME=~/android-sdk
##    - QEMU_AUDIO_DRV=none
##    - ANDROID_SDK_ROOT=$ANDROID_HOME
#
##before_install:
##  - touch $HOME/.android/repositories.cfg
##  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip" -O commandlinetools.zip
##  - unzip commandlinetools.zip -d $ANDROID_HOME/
##  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
##  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME
#
#before_script:
#  # Create and start emulator
#  - android list targets
#  #- chmod +x gradlew
#  - echo no | android create avd --force -n test -t android-29 --abi x86
#  - emulator -avd test -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
#
#script: ./gradlew connectedAndroidTest

language: android
dist: trusty
android:
  components:
    # explicitly state required components
    - tools
    - tools
    - platform-tools
    - build-tools-30.0.2

    # The SDK version used by the project
    - android-30

    # Addons
    - addon
    - extra
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository

    # System images needed to run emulator
    - sys-img-x86-android-29

env:
  global:
    - SDKGET=~/android_sdk/tools/bin/sdkmanager
    - AVDMAKE=~/android_sdk/tools/bin/avdmanager

before_install:
  # use sdkmanager to install all the tools
    $SDKGET "build-tools;29.0.2"
    $SDKGET "emulator"
    $SDKGET "platform-tools"
    $SDKGET "platforms;android-24"
    $SDKGET "system-images;android-24;default;armeabi-v7a" # Nougat 7.0
    $SDKGET "system-images;android-26;default;x86" # Orea 8.0

    # use avdmanager to create the virtual devices
    $AVDMAKE create avd -n Nexus5_7.0_api24 -k "system-images;android-24;default;armeabi-v7a" --device "Nexus 5" # 1920 x 1080
    $AVDMAKE create avd -n Nexus6P_8.0_api26 -k "system-images;android-26;default;x86" --device "Nexus 6P" # 2560 x 1440

before_script:
  # Emulator management: Create, Start, Wait

  # List available emulator targets
  - android list targets
  - sdkmanager --list
  #- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 100M # use for non x86
  - echo no | android create avd --force -n test -t android-29 --abi x86 -c 100M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradew build connectedCheck

# When using gradle (dependency caching), do following to avoid uploading cache after every build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache