# Helpful resources:
# https://travis-ci.community/t/add-kvm-support/1406/8
# https://docs.travis-ci.com/user/languages/android/
# https://config.travis-ci.com/
os: linux
language: android
dist: trusty
jdk: openjdk11
sudo: required

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    #- ANDROID_HOME=~/ # may results in broken avd path?
    #- ANDROID_SDK_ROOT=~/android-sdk/system-images/android-29

android:
  components:
    # explicitly state required components
    - tools
    - tools
    - platform-tools
    - build-tools-30.0.2

    # The SDK version used by the project
    - android-29

    # Addons
    - add-on
    - extra

  licenses:
    - 'android-.+'
    - 'mips-.+'
    - 'google-.+'

before_install:
  # Update SDK manager to work with jdk 11
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - echo $PATH
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --update --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager tools --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-29" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;30.0.2" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "system-images;android-29;google_apis;x86" --sdk_root=$ANDROID_HOME
  # Emulator Creation (x86 no hardware acceleration)
  - echo no | $ANDROID_HOME/cmdline-tools/bin/avdmanager create avd --force -n my_avd -k "system-images;android-29;google_apis;x86"
  - $ANDROID_SDK_ROOT=$ANDROID_HOME
  - ls $ANDROID_HOME
  - ls $ANDROID_SDK_ROOT
  - PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/bin

  # Emulator Start
  - $ANDROID_HOME/emulator/emulator -avd my_avd -memory 1500 -no-accel -gpu swiftshader -skin 720x1280 -camera-back none -camera-front none -no-boot-anim -no-window &

before_script:
#  - ls ~/system-images/android-29
#  - cat ~/.android/avd/my_avd.ini
#  - ls ~/
  - ls $ANDROID_HOME
  #- ls ~/.android/avd
  - android list target
  #- $ANDROID_HOME/cmdline-tools/bin/sdkmanager --list --sdk_root=$ANDROID_HOME
  - emulator -list-avds

  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script: ./gradlew build connectedCheck

# When using gradle (dependency caching), do following to avoid uploading cache after every build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache